USE [master];
GO

IF EXISTS (SELECT 1 FROM sys.databases WHERE name = 'AGSAuth')
    BEGIN
        ALTER DATABASE [AGSAuth] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
        DROP DATABASE [AGSAuth];
    END
GO

CREATE DATABASE [AGSAuth];
GO

ALTER DATABASE [AGSAuth] SET ALLOW_SNAPSHOT_ISOLATION ON;
ALTER DATABASE [AGSAuth] SET READ_COMMITTED_SNAPSHOT ON;
GO

USE [AGSAuth];
GO

CREATE SCHEMA [Resource];
GO
CREATE SCHEMA [Client];
GO
CREATE SCHEMA [Person];
GO
CREATE SCHEMA [Partner];
GO
CREATE SCHEMA [Token];
GO