USE [master]
GO

CREATE DATABASE [AGSAuth]
    CONTAINMENT = NONE
    ON PRIMARY
    ( NAME = N'AGSAuth', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AGSAuth.mdf' , SIZE = 8 MB , MAXSIZE = 1024 MB, FILEGROWTH = 65536 KB ),
    FILEGROUP [DATA]
        ( NAME = N'Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AGSAuth_Data.ndf' , SIZE = 8 MB , MAXSIZE = 1024 MB , FILEGROWTH = 65536 KB ),
    FILEGROUP [INDEX]
        ( NAME = N'Index', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AGSAuth_Index.ndf' , SIZE = 8 MB , MAXSIZE = 1024 MB , FILEGROWTH = 65536 KB ),
    FILEGROUP [RESOURCE_DATA]
        (NAME = N'ResourceData', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AGSAuth_ResourceData.ndf' , SIZE = 8 MB , MAXSIZE = 1024 MB , FILEGROWTH = 65536 KB),
    FILEGROUP [RESOURCE_INDEX]
        (NAME = N'ResourceIndex', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AGSAuth_ResourceIndex.ndf' , SIZE = 8 MB , MAXSIZE = 1024 MB , FILEGROWTH = 65536 KB),
    FILEGROUP [CLIENT_DATA]
        (NAME = N'ClientData', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AGSAuth_ClientData.ndf' , SIZE = 8 MB , MAXSIZE = 1024 MB , FILEGROWTH = 65536 KB),
    FILEGROUP [CLIENT_INDEX]
        (NAME = N'ClientIndex', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AGSAuth_ClientIndex.ndf' , SIZE = 8 MB , MAXSIZE = 1024 MB , FILEGROWTH = 65536 KB),
    FILEGROUP [TOKEN_DATA]
        (NAME = N'TokenData', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AGSAuth_TokenData.ndf' , SIZE = 8 MB , MAXSIZE = 1024 MB , FILEGROWTH = 65536 KB),
    FILEGROUP [TOKEN_INDEX]
        (NAME = N'TokenIndex', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AGSAuth_TokenIndex.ndf' , SIZE = 8 MB , MAXSIZE = 1024 MB , FILEGROWTH = 65536 KB),
    FILEGROUP [USER_DATA]
        (NAME = N'UserData', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AGSAuth_UserData.ndf', SIZE = 8 MB , MAXSIZE = 1024 MB , FILEGROWTH = 65536 KB),
    FILEGROUP [USER_INDEX]
        (NAME = N'UserIndex', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AGSAuth_UserIndex.ndf', SIZE = 8 MB , MAXSIZE = 1024 MB , FILEGROWTH = 65536 KB)
    LOG ON
    ( NAME = N'AGSAuth_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AGSAuth_log.ldf' , SIZE = 128 MB , MAXSIZE = 2048 MB , FILEGROWTH = 65536 KB )
GO


ALTER DATABASE [AGSAuth] SET COMPATIBILITY_LEVEL = 150
GO


IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
    BEGIN
        EXEC [AGSAuth].[dbo].[sp_fulltext_database] @action = 'enable'
    end
GO

-- Enable snapshot isolation by default
ALTER DATABASE [AGSAuth] SET ALLOW_SNAPSHOT_ISOLATION ON
GO

-- Read committed snapshot on
ALTER DATABASE [AGSAuth] SET READ_COMMITTED_SNAPSHOT ON
GO

-- RECOVERY MODEL -- NEED TRANSACTION LOG BACKUP
ALTER DATABASE [AGSAuth] SET RECOVERY FULL
GO

ALTER DATABASE [AGSAuth] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [AGSAuth] SET ANSI_NULLS OFF
GO

ALTER DATABASE [AGSAuth] SET ANSI_PADDING OFF
GO

ALTER DATABASE [AGSAuth] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [AGSAuth] SET ARITHABORT OFF
GO

ALTER DATABASE [AGSAuth] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [AGSAuth] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [AGSAuth] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [AGSAuth] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [AGSAuth] SET CURSOR_DEFAULT GLOBAL
GO

ALTER DATABASE [AGSAuth] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [AGSAuth] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [AGSAuth] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [AGSAuth] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [AGSAuth] SET DISABLE_BROKER
GO

ALTER DATABASE [AGSAuth] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [AGSAuth] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [AGSAuth] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [AGSAuth] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [AGSAuth] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [AGSAuth] SET MULTI_USER
GO

ALTER DATABASE [AGSAuth] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [AGSAuth] SET DB_CHAINING OFF
GO

ALTER DATABASE [AGSAuth] SET FILESTREAM ( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [AGSAuth] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [AGSAuth] SET DELAYED_DURABILITY = DISABLED
GO

-- ALTER DATABASE [AGSAuth] SET ACCELERATED_DATABASE_RECOVERY = OFF
-- GO

ALTER DATABASE [AGSAuth] SET READ_WRITE
GO

ALTER DATABASE [AGSAuth] SET QUERY_STORE = ON
GO

ALTER DATABASE [AGSAuth] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, MAX_STORAGE_SIZE_MB = 100, INTERVAL_LENGTH_MINUTES = 60, MAX_PLANS_PER_QUERY = 200, QUERY_CAPTURE_MODE = AUTO, QUERY_CAPTURE_MODE = AUTO )
GO

USE [AGSAuth]
GO

CREATE SCHEMA [Resource]
GO

CREATE SCHEMA [Client]
GO

CREATE SCHEMA [Person]
GO

CREATE SCHEMA [Partner]
GO

CREATE SCHEMA [Token]
GO